### ISSUE TITLE
rsync needs to be two-way

### ISSUE THREAD

**Issue by jpat14** [itpsu1/itcomm-nittany-vagrant#2]
Files should sync in both directions.

**Comment by heyMP** [comment]
Here are the docs that I've been references http://docs.vagrantup.com/v2/synced-folders/rsync.html

**Comment by jpat14** [comment]
Got unidirectional rsync working well. Other options would be NFS shares, ect. For now, we're going to use rsync. If we run into issues with unidirectional syncing, we can reevaluate this issue.
